-- ⚠️ ไฟล์นี้ไม่ใช่แหล่งอ้างอิงอีกต่อไป
--
-- เนื้อหาเดิมของไฟล์นี้ล้าสมัยและทำให้เข้าใจผิด — มันชี้ตาราง "public.users"
-- (ตารางจริงคือ public.skc_users ดู @@map ใน prisma/schema.prisma) และเขียน
-- คอลัมน์สิทธิ์ can_post_jobs / can_evaluate / can_approve_users /
-- can_manage_credentials ซึ่งไม่มีอยู่ในสคีมาแล้ว ระบบสิทธิ์ปัจจุบันคำนวณจาก
-- skc_role_permissions บวก override รายคน ตอนอ่านค่า (src/lib/permissions.ts)
--
-- 19 ส.ค. 2569 การเชื่อไฟล์นี้ทำให้มี commit ที่พยายามอัปเดตคอลัมน์ที่ไม่มีจริง
-- หลุดขึ้น main ไปหนึ่งรอบ จึงล้างเนื้อหาทิ้งเพื่อไม่ให้เกิดซ้ำ
--
-- ต้องการดู trigger ที่รันอยู่จริงบน production:
--
--   SELECT unnest(string_to_array(pg_get_functiondef(tgfoid), E'\n')) AS line
--   FROM pg_trigger WHERE tgname = 'on_auth_user_created';
--
-- เวอร์ชันที่ถือเป็นปัจจุบันของ trigger นี้อยู่ที่:
--   supabase/2026-08-19-signup-trigger-keep-profile-fields.sql
